Avoid forking a subshell for error reporting
We can instead use bash's compound command syntax, which is slightly
more efficient.

diff --git a/gh-cat b/gh-cat
--- a/gh-cat
+++ b/gh-cat
@@ -109,6 +109,8 @@ _cat() {
 
 for path in "${paths[@]}"; do
   curl -fsL --oauth2-bearer "$token" \
-    "https://raw.githubusercontent.com/$repo/$branch/$path" | _cat "$path" ||
-    (echo "$repo: $path: not found or unavailable" >&2; exit 1)
+    "https://raw.githubusercontent.com/$repo/$branch/$path" | _cat "$path" || {
+      echo "$repo: $path: not found or unavailable" >&2
+      exit 1
+    }
 done
