Also verify that gh is available
This might only be an issue when we're running as a standalone script.

diff --git a/gh-cat b/gh-cat
--- a/gh-cat
+++ b/gh-cat
@@ -67,10 +67,12 @@ if [[ ! $repo || ${#paths[@]} == 0 ]]; then
   usage
 fi
 
-if ! type -p curl >/dev/null; then
-  echo "error: curl not found on the system" >&2
-  exit 1
-fi
+for cmd in curl gh; do
+  if ! type -p "$cmd" >/dev/null; then
+    echo "error: $cmd not found on the system" >&2
+    exit 1
+  fi
+done
 
 if [[ ! $repo =~ .*/.* ]]; then
   user="$(gh config get -h github.com user)"
